name: abc

on: push

jobs:
  abc:
    name: abc project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run abc
        uses: github/SecureWebAppWithGitHubAction@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
